export const MOCK_DASHBOARD_STATS = {
  totalAppsMonitored: 47,
  activeConnections: 234,
  alertsToday: 12,
  criticalAlerts: 3,
  privacyScore: 78,
  dataLeaksBlocked: 156,
  bandwidthAnalyzed: '2.4 GB',
  uptime: '99.97%',
};

export const MOCK_TRAFFIC_DATA = [
  { timestamp: '00:00', inbound: 120, outbound: 80, blocked: 12, encrypted: 95 },
  { timestamp: '02:00', inbound: 90, outbound: 60, blocked: 8, encrypted: 78 },
  { timestamp: '04:00', inbound: 45, outbound: 30, blocked: 5, encrypted: 40 },
  { timestamp: '06:00', inbound: 80, outbound: 55, blocked: 10, encrypted: 70 },
  { timestamp: '08:00', inbound: 200, outbound: 150, blocked: 25, encrypted: 180 },
  { timestamp: '10:00', inbound: 320, outbound: 250, blocked: 35, encrypted: 290 },
  { timestamp: '12:00', inbound: 380, outbound: 300, blocked: 40, encrypted: 340 },
  { timestamp: '14:00', inbound: 350, outbound: 280, blocked: 38, encrypted: 310 },
  { timestamp: '16:00', inbound: 290, outbound: 220, blocked: 30, encrypted: 260 },
  { timestamp: '18:00', inbound: 250, outbound: 180, blocked: 22, encrypted: 230 },
  { timestamp: '20:00', inbound: 180, outbound: 130, blocked: 18, encrypted: 160 },
  { timestamp: '22:00', inbound: 140, outbound: 100, blocked: 14, encrypted: 120 },
];

export const MOCK_THREAT_DISTRIBUTION = [
  { category: 'Data Exfiltration', count: 23, severity: 'critical' as const },
  { category: 'Tracker Activity', count: 89, severity: 'high' as const },
  { category: 'Unencrypted Traffic', count: 45, severity: 'medium' as const },
  { category: 'Suspicious DNS', count: 34, severity: 'high' as const },
  { category: 'Permission Abuse', count: 12, severity: 'critical' as const },
  { category: 'Location Tracking', count: 67, severity: 'medium' as const },
];

export const MOCK_APPS = [
  {
    id: '1',
    packageName: 'com.social.media',
    appName: 'SocialConnect',
    riskLevel: 'high' as const,
    privacyScore: 32,
    connectionsToday: 456,
    dataTransferred: '145 MB',
    lastActivity: '2026-03-10T23:15:00Z',
    status: 'active' as const,
    permissions: ['INTERNET', 'CAMERA', 'LOCATION', 'CONTACTS', 'MICROPHONE'],
  },
  {
    id: '2',
    packageName: 'com.messaging.app',
    appName: 'QuickChat',
    riskLevel: 'medium' as const,
    privacyScore: 58,
    connectionsToday: 234,
    dataTransferred: '78 MB',
    lastActivity: '2026-03-10T23:10:00Z',
    status: 'active' as const,
    permissions: ['INTERNET', 'CAMERA', 'CONTACTS', 'STORAGE'],
  },
  {
    id: '3',
    packageName: 'com.secure.browser',
    appName: 'SecureBrowse',
    riskLevel: 'low' as const,
    privacyScore: 92,
    connectionsToday: 120,
    dataTransferred: '256 MB',
    lastActivity: '2026-03-10T23:05:00Z',
    status: 'active' as const,
    permissions: ['INTERNET', 'STORAGE'],
  },
  {
    id: '4',
    packageName: 'com.fitness.tracker',
    appName: 'FitTrack Pro',
    riskLevel: 'critical' as const,
    privacyScore: 15,
    connectionsToday: 789,
    dataTransferred: '312 MB',
    lastActivity: '2026-03-10T22:55:00Z',
    status: 'active' as const,
    permissions: ['INTERNET', 'LOCATION', 'BODY_SENSORS', 'ACTIVITY_RECOGNITION', 'STORAGE'],
  },
  {
    id: '5',
    packageName: 'com.weather.forecast',
    appName: 'WeatherNow',
    riskLevel: 'medium' as const,
    privacyScore: 61,
    connectionsToday: 56,
    dataTransferred: '12 MB',
    lastActivity: '2026-03-10T22:30:00Z',
    status: 'active' as const,
    permissions: ['INTERNET', 'LOCATION'],
  },
  {
    id: '6',
    packageName: 'com.gaming.arcade',
    appName: 'ArcadeBlast',
    riskLevel: 'high' as const,
    privacyScore: 28,
    connectionsToday: 345,
    dataTransferred: '89 MB',
    lastActivity: '2026-03-10T22:00:00Z',
    status: 'active' as const,
    permissions: ['INTERNET', 'STORAGE', 'PHONE', 'CAMERA'],
  },
];

export const MOCK_ALERTS = [
  {
    id: '1',
    timestamp: '2026-03-10T23:12:00Z',
    severity: 'critical' as const,
    title: 'Data Exfiltration Detected',
    description: 'FitTrack Pro is sending device identifiers to a third-party analytics server in an unencrypted channel.',
    source: 'Network Monitor',
    packageName: 'com.fitness.tracker',
    status: 'active' as const,
    category: 'Data Leak',
  },
  {
    id: '2',
    timestamp: '2026-03-10T23:05:00Z',
    severity: 'critical' as const,
    title: 'Unauthorized Location Access',
    description: 'SocialConnect is accessing precise GPS location in background every 30 seconds without user interaction.',
    source: 'Permission Monitor',
    packageName: 'com.social.media',
    status: 'active' as const,
    category: 'Permission Abuse',
  },
  {
    id: '3',
    timestamp: '2026-03-10T22:48:00Z',
    severity: 'high' as const,
    title: 'Tracker Domain Communication',
    description: 'ArcadeBlast is communicating with 12 known tracker domains including advertising networks.',
    source: 'DNS Monitor',
    packageName: 'com.gaming.arcade',
    status: 'active' as const,
    category: 'Tracker Activity',
  },
  {
    id: '4',
    timestamp: '2026-03-10T22:30:00Z',
    severity: 'high' as const,
    title: 'Unencrypted Data Transfer',
    description: 'WeatherNow is transmitting user preferences over unencrypted HTTP connections.',
    source: 'Traffic Analyzer',
    packageName: 'com.weather.forecast',
    status: 'active' as const,
    category: 'Unencrypted Traffic',
  },
  {
    id: '5',
    timestamp: '2026-03-10T22:15:00Z',
    severity: 'medium' as const,
    title: 'Excessive Background Connections',
    description: 'QuickChat initiated 34 connections in the last hour while in background mode.',
    source: 'Connection Monitor',
    packageName: 'com.messaging.app',
    status: 'active' as const,
    category: 'Suspicious Activity',
  },
  {
    id: '6',
    timestamp: '2026-03-10T21:50:00Z',
    severity: 'medium' as const,
    title: 'Contact List Access',
    description: 'SocialConnect read the entire contact list and transmitted data to its servers.',
    source: 'Permission Monitor',
    packageName: 'com.social.media',
    status: 'dismissed' as const,
    category: 'Data Collection',
  },
  {
    id: '7',
    timestamp: '2026-03-10T21:30:00Z',
    severity: 'low' as const,
    title: 'App Version Outdated',
    description: 'SecureBrowse is running an older version that may have known vulnerabilities.',
    source: 'Version Monitor',
    packageName: 'com.secure.browser',
    status: 'active' as const,
    category: 'Maintenance',
  },
];

export const MOCK_REPORTS = [
  {
    id: '1',
    title: 'Weekly Privacy Audit Report',
    type: 'privacy_audit' as const,
    status: 'completed' as const,
    createdAt: '2026-03-10T08:00:00Z',
    completedAt: '2026-03-10T08:15:00Z',
    fileSize: '2.4 MB',
    summary: 'Comprehensive privacy audit covering 47 monitored applications with 3 critical findings.',
  },
  {
    id: '2',
    title: 'Network Traffic Analysis - March',
    type: 'traffic_analysis' as const,
    status: 'completed' as const,
    createdAt: '2026-03-09T12:00:00Z',
    completedAt: '2026-03-09T12:30:00Z',
    fileSize: '5.1 MB',
    summary: 'Detailed analysis of network traffic patterns showing 156 blocked data leak attempts.',
  },
  {
    id: '3',
    title: 'Threat Assessment Report',
    type: 'threat_assessment' as const,
    status: 'completed' as const,
    createdAt: '2026-03-08T14:00:00Z',
    completedAt: '2026-03-08T14:45:00Z',
    fileSize: '3.8 MB',
    summary: 'Threat landscape assessment identifying 5 high-risk applications requiring immediate action.',
  },
  {
    id: '4',
    title: 'Compliance Status Report',
    type: 'compliance' as const,
    status: 'generating' as const,
    createdAt: '2026-03-10T22:00:00Z',
    summary: 'Generating compliance report against GDPR and CCPA standards.',
  },
];
